// Adversarial parity tests between the Rust core (crates/cairn-core) and the
// TypeScript link helpers and renderer.
//
// The fixtures are generated by crates/cairn-core/tests/adv_links_fixture.rs
// (which also fails if they are stale):
//   cargo test -p cairn-core --test adv_links_fixture
//   ADV_LINKS_REGEN=1 cargo test -p cairn-core --test adv_links_fixture   # rewrite
// Run here:  cd app && npx vitest run src/lib/adv_links.test.ts
//
// Tests named "FINDING-NNN ..." are regression tests for a defect. The other
// tests are scenarios that held up.

import { describe, expect, it } from "vitest";
import resolutionFixture from "../../../crates/cairn-core/tests/fixtures/adv_links_resolution.json";
import parseFixture from "../../../crates/cairn-core/tests/fixtures/adv_links_parse.json";
import livePreviewSource from "./editor/livePreview.ts?raw";
import { LinkIndex, splitWikilink } from "./links";
import { headingsOf, renderUnsafe, stripFrontmatter } from "./markdown";
import { extractSection } from "./embeds";
import type { FileStat } from "./types";

interface WikiCase {
  kind: "wiki" | "embed";
  source: string;
  raw: string;
  inner: string;
  target: string;
  subpath: string | null;
  alias: string | null;
  rust: string | null;
  plan: string | null;
}
interface MdCase {
  kind: "md" | "mdimage";
  source: string;
  raw: string;
  url: string;
  parsedTarget: string | null;
  parsedSubpath: string | null;
  rust: string | null;
  rustClick: string | null;
}
type Case = WikiCase | MdCase;
interface Vault {
  files: string[];
  dirs: string[];
  cases: Case[];
  linkText: { path: string; text: string | null; source: string; rust: string | null }[];
}

const vaults = (resolutionFixture as unknown as { vaults: Vault[] }).vaults;

const f = (path: string, kind: "file" | "dir" = "file"): FileStat => ({ path, kind, size: 0, mtime: 0 });
const indexFor = (v: { files: string[]; dirs?: string[] }) =>
  new LinkIndex([...(v.dirs ?? []).map((d) => f(d, "dir")), ...v.files.map((p) => f(p))]);
const utf8 = (s: string) => new TextEncoder().encode(s).length;
const cps = (s: string) => [...s].length;

/** Why TS and Rust disagree on a resolution, if the reason is known.
 *  `raw` is the link text before either side trimmed it. Backslashes and
 *  the U+0085/U+FEFF trim set (FINDING-185) are not a reason. */
function classify(files: string[], raw: string, ts: string | null, rust: string | null): string {
  if (ts && rust) {
    if (Math.sign(ts.length - rust.length) !== Math.sign(utf8(ts) - utf8(rust))) return "length-units";
    if (ts.length === rust.length && utf8(ts) === utf8(rust)) return "string-order";
  }
  void files;
  void raw;
  return "other";
}

function wikiDiffs() {
  const out: { cat: string; files: string[]; c: WikiCase; ts: string | null }[] = [];
  for (const v of vaults) {
    const idx = indexFor(v);
    for (const c of v.cases) {
      if (c.kind !== "wiki" && c.kind !== "embed") continue;
      const parts = splitWikilink(c.inner);
      const ts = idx.resolve(parts.target, c.source);
      if (ts !== c.rust) out.push({ cat: classify(v.files, c.inner, ts, c.rust), files: v.files, c, ts });
    }
  }
  return out;
}

describe("link resolution parity with the Rust index (random fixture)", () => {
  it("fixture is present and large", () => {
    const n = vaults.reduce((a, v) => a + v.cases.length, 0);
    expect(vaults.length).toBeGreaterThanOrEqual(100);
    expect(n).toBeGreaterThanOrEqual(2000);
  });

  it("splitWikilink matches Rust split_wikilink_inner", () => {
    const bad: string[] = [];
    for (const v of vaults)
      for (const c of v.cases) {
        if (c.kind !== "wiki" && c.kind !== "embed") continue;
        const p = splitWikilink(c.inner);
        if (p.target !== c.target || p.subpath !== c.subpath || p.alias !== c.alias)
          bad.push(JSON.stringify({ inner: c.inner, ts: p, rust: [c.target, c.subpath, c.alias] }));
      }
    expect(bad).toEqual([]);
  });

  it("LinkIndex.resolve agrees with Index::resolve outside the known disagreement categories", () => {
    const diffs = wikiDiffs();
    const counts: Record<string, number> = {};
    for (const d of diffs) counts[d.cat] = (counts[d.cat] ?? 0) + 1;
    console.log("TS vs Rust wikilink resolution disagreements:", counts);
    const other = diffs.filter((d) => d.cat === "other").map((d) => JSON.stringify({ files: d.files, source: d.c.source, target: d.c.target, ts: d.ts, rust: d.c.rust }));
    expect(other).toEqual([]);
  });

  it("LinkIndex.exists agrees with whether Rust resolves the target (unresolved styling)", () => {
    const bad: string[] = [];
    for (const v of vaults) {
      const idx = indexFor(v);
      for (const c of v.cases) {
        if (c.kind !== "wiki" && c.kind !== "embed") continue;
        const t = splitWikilink(c.inner).target;
        if (!t) continue;
        if (idx.exists(t, c.source) !== (c.rust !== null) && classify(v.files, c.inner, null, null) === "other") bad.push(JSON.stringify({ files: v.files, t, rust: c.rust }));
      }
    }
    expect(bad).toEqual([]);
  });

  it("TS percent-decoding of Markdown link URLs matches the Rust parser (except CommonMark backslash escapes)", () => {
    const bad: string[] = [];
    for (const v of vaults)
      for (const c of v.cases) {
        if (c.kind !== "md" || c.parsedTarget === null || c.url.includes("\\")) continue;
        // livePreview.ts / setup.ts linkAtPos: strip <>, split at #, decodeURIComponent
        const href = c.url.replace(/^<|>$/g, "");
        let p = href.split("#")[0];
        try {
          p = decodeURIComponent(p);
        } catch {}
        if (p !== c.parsedTarget) bad.push(JSON.stringify({ url: c.url, ts: p, rust: c.parsedTarget }));
      }
    expect(bad).toEqual([]);
  });
});

describe("findings: TS vs Rust resolution", () => {
  it("FINDING-180: shortest-path tie-break counts characters on both sides", () => {
    // PLAN says "shortest path": "ééé/Note.md" has 11 characters (14 UTF-8
    // bytes) and "abcd/Note.md" 12. Rust Index::resolve counts characters too.
    const idx = indexFor({ files: ["ééé/Note.md", "abcd/Note.md"] });
    expect(idx.resolve("Note", "x.md")).toBe("ééé/Note.md");
    // An astral character is one character (two UTF-16 units).
    expect(indexFor({ files: ["😀😀😀/Note.md", "abcd/Note.md"] }).resolve("Note", "x.md")).toBe("😀😀😀/Note.md");
  });

  it("FINDING-180: alphabetical tie-break is code point order on both sides", () => {
    // Same length in characters (10) and in UTF-16 units (11); Rust orders
    // U+FF71 before U+1F600, and so must TS (comparing UTF-16 units puts the
    // surrogate 0xD83D first). (Was "😀/Note.md" and "ｱa/Note.md": counted in
    // characters, those differ in length and never reach this step.)
    const idx = indexFor({ files: ["😀ｱ/Note.md", "ｱ😀/Note.md"] });
    expect(idx.resolve("Note", "x.md")).toBe("ｱ😀/Note.md");
  });

  it("FINDING-185: LinkIndex accepts backslash separators like the core", () => {
    // Rust replaces '\\' with '/', so [[sub\Note]] resolves in the core
    // (backlinks, click); the editor styled it as unresolved and image
    // embeds like ![[img\pic.png]] did not render.
    const idx = indexFor({ files: ["sub/Note.md", "img/pic.png"] });
    expect(idx.resolve("sub\\Note", "x.md")).toBe("sub/Note.md");
    expect(idx.resolve("\\sub\\Note", "x.md")).toBe("sub/Note.md");
    expect(idx.exists("img\\pic.png")).toBe(true);
    expect(previewImagePath("![[img\\pic.png]]", idx, "x.md")).toBe("img/pic.png");
  });

  it("FINDING-185: wikilinks trim U+0085 but not U+FEFF, like the core", () => {
    // Rust str::trim removes U+0085 (NEL) but not U+FEFF; JS trim() is the opposite.
    expect(splitWikilink("Note\ufeff").target).toBe("Note\ufeff");
    expect(splitWikilink("\u0085Note#\u0085Sub\u0085|\u0085Alias")).toEqual({ target: "Note", subpath: "Sub", alias: "Alias" });
  });

  it("random fixture has backslash and U+0085/U+FEFF links, so the checks above cover FINDING-185", () => {
    // These were the "backslash" and "trim-set" disagreement categories.
    const wiki = vaults.flatMap((v) => v.cases).filter((c): c is WikiCase => c.kind === "wiki" || c.kind === "embed");
    expect(wiki.filter((c) => c.target.includes("\\")).length).toBeGreaterThanOrEqual(10);
    expect(wiki.filter((c) => /[\u0085\ufeff]/.test(c.inner)).length).toBeGreaterThanOrEqual(10);
  });
});

/** The image path the preview would load for `raw`, or null. */
function previewImagePath(raw: string, idx: LinkIndex, sourcePath: string): string | null {
  const html = renderUnsafe(raw, { links: idx, sourcePath });
  const m = /<img[^>]*src="vault:\/\/localhost\/([^"]*)"/.exec(html);
  if (!m) return null;
  return m[1].split("/").map(decodeURIComponent).join("/").replace(/&amp;/g, "&");
}

describe("Markdown image resolution in the preview vs the core", () => {
  it("preview images load the file the core resolves (random fixture, excluding known categories)", () => {
    const bad: string[] = [];
    const counts: Record<string, number> = {};
    for (const v of vaults) {
      const idx = indexFor(v);
      for (const c of v.cases) {
        if (c.kind !== "mdimage") continue;
        const shown = previewImagePath(c.raw, idx, c.source);
        // What actually loads: only an existing file with that exact path.
        const loads = shown !== null && v.files.includes(shown) ? shown : null;
        if (loads === c.rust) continue;
        let cat = shown && !v.files.includes(shown) ? "broken-image" : classify(v.files, c.url, loads, c.rust);
        if (cat === "broken-image") {
          if (c.rust && /\.(md|markdown)$/i.test(c.rust)) cat = "broken-image:target-is-a-note";
          else if (v.files.includes(shown!.normalize("NFC"))) cat = "broken-image:nfd"; // FINDING-179
          else cat = "other"; // case-only and suffix matches: FINDING-086
        }
        counts[cat] = (counts[cat] ?? 0) + 1;
        if (cat === "other") bad.push(JSON.stringify({ files: v.files, source: c.source, raw: c.raw, shown, rust: c.rust }));
      }
    }
    console.log("preview image vs core disagreements:", counts);
    expect(bad).toEqual([]);
  });

  it("FINDING-086: preview loads the file the core resolves when the relative path only matches by suffix", () => {
    // Core: ![x](a/pic.png) from n.md has no a/pic.png, falls back to name
    // matching and resolves z/a/pic.png. The preview must not load
    // vault://localhost/a/pic.png (exists() is a suffix match), a 404.
    const idx = indexFor({ files: ["z/a/pic.png", "n.md"] });
    expect(previewImagePath("![x](a/pic.png)", idx, "n.md")).toBe("z/a/pic.png");
  });

  it("FINDING-086: preview loads the file the core resolves when the relative path differs only in case", () => {
    // Core resolves case-insensitively to img/pic.png; the preview must not
    // load img/Pic.png, which does not exist on a case-sensitive file system.
    const idx = indexFor({ files: ["img/pic.png", "n.md"] });
    expect(previewImagePath("![x](img/Pic.png)", idx, "n.md")).toBe("img/pic.png");
  });

  it("FINDING-086: the part of an image URL after '#' is not part of the path, as in the core", () => {
    const idx = indexFor({ files: ["img/pic.png", "n.md"] });
    expect(previewImagePath("![x](img/pic.png#frag)", idx, "n.md")).toBe("img/pic.png");
    expect(previewImagePath("![x](img/Pic.png#frag)", idx, "n.md")).toBe("img/pic.png");
  });

  it("wikilink image embeds load what the core resolves", () => {
    const idx = indexFor({ files: ["img/pic.png", "a/pic.png", "a/n.md"] });
    expect(previewImagePath("![[pic.png|100]]", idx, "a/n.md")).toBe("a/pic.png");
    expect(previewImagePath("![[PIC.PNG]]", idx, "n.md")).toBe("a/pic.png");
  });
});

describe("autocomplete link text round trip", () => {
  it("TS linkText matches the text the Rust fixture assumed", () => {
    const bad: string[] = [];
    for (const v of vaults) {
      const idx = indexFor(v);
      for (const c of v.linkText) if (idx.linkText(c.path) !== c.text) bad.push(`${c.path}: ts=${idx.linkText(c.path)} rust-emulated=${c.text}`);
    }
    expect(bad).toEqual([]);
  });

  it("FINDING-184: linkText for a note named x.md.md resolves back in the core", () => {
    const v = vaults.flatMap((v) => v.linkText).find((c) => c.path.endsWith("x.md.md") && c.rust !== c.path);
    expect(v).toBeUndefined();
    expect(indexFor({ files: ["x.md.md"] }).linkText("x.md.md")).toBe("x.md.md");
  });

  it("FINDING-184: a file whose name contains # | [ or ] (created outside Cairn) gets no link text, not a link to another file", () => {
    // No wikilink can name these: [[C# notes]] is C with the heading "notes".
    // The autocomplete leaves them out.
    const idx = indexFor({ files: ["C# notes.md", "C.md", "a|b.md", "x[1].md"] });
    expect(idx.linkText("C# notes.md")).toBeNull();
    expect(idx.linkText("a|b.md")).toBeNull();
    expect(idx.linkText("x[1].md")).toBeNull();
    expect(idx.linkText("C.md")).toBe("C");
  });

  it("FINDING-184: of case-variant twins, only the one wikilinks resolve to gets link text", () => {
    // Linux allows a/Note.md and a/note.md side by side. Resolution is
    // case-insensitive, so every wikilink to either one reaches a/Note.md.
    const idx = indexFor({ files: ["a/Note.md", "a/note.md"] });
    expect(idx.linkText("a/Note.md")).toBe("a/Note");
    expect(idx.linkText("a/note.md")).toBeNull();
  });

  it("FINDING-184: link text always resolves back to its file (random fixture)", () => {
    const bad: string[] = [];
    for (const v of vaults) {
      const idx = indexFor(v);
      for (const p of v.files) {
        const t = idx.linkText(p);
        if (t !== null && idx.resolve(splitWikilink(t).target, "notes/daily/Source.md") !== p) bad.push(`${p}: [[${t}]]`);
      }
    }
    expect(bad).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// Parser parity
// ---------------------------------------------------------------------------

interface ParseCase {
  src: string;
  wiki: { target: string; subpath: string | null; embed: boolean }[];
  md: { target: string; embed: boolean }[];
  bodyTags: string[];
  fmTags: string[];
  hasFrontmatter: boolean;
  bodyStart: number;
  bodyStartUtf16: number;
}
const pf = parseFixture as unknown as { cases: ParseCase[]; headings: { src: string; headings: { level: number; text: string; line: number }[] }[] };

function decodeHtml(s: string): string {
  return s.replace(/&quot;/g, '"').replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&");
}

/** What the preview renders as links/embeds/tags for `src`. */
function previewParse(src: string) {
  const html = renderUnsafe(src, { links: null });
  const wiki: { target: string; embed: boolean }[] = [];
  const re = /<a class="internal-link[^"]*" data-href="([^"]*)"|<span class="embed" data-target="([^"]*)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(html))) {
    if (m[1] !== undefined) {
      const href = decodeHtml(m[1]);
      const i = href.indexOf("#");
      wiki.push({ target: i >= 0 ? href.slice(0, i) : href, embed: false });
    } else wiki.push({ target: decodeHtml(m[2]), embed: true });
  }
  const tags = [...html.matchAll(/data-tag="([^"]*)"/g)].map((x) => decodeHtml(x[1]).toLowerCase());
  return { wiki, tags: [...new Set(tags)] };
}

/** Tags the Live Preview editor decorates, using the regex from livePreview.ts. */
const lpTagRe = (() => {
  const m = /const TAG_RE = \/(.*)\/([a-z]*);/.exec(livePreviewSource);
  if (!m) throw new Error("TAG_RE not found in livePreview.ts");
  return new RegExp(m[1], m[2]);
})();

function rustWiki(c: ParseCase) {
  return c.wiki.filter((w) => w.target !== "").map((w) => ({ target: w.target, embed: w.embed }));
}

const KNOWN_PARSE_DIFFS: Record<string, string> = {
  "[[A]](x.md)": "core: Markdown link with text [A]; preview: wikilink A (CommonMark vs plugin order)",
  "[[A|B|C]] [[A#B#C]] [[#Local]] [[ ]] [[|x]]": "preview renders [[ ]] and [[|x]] as (dead) links",
  "[see #inlink [[InLink]]](x.md)": "preview renders a wikilink and a tag inside the link text (nested <a>); the core ignores both",
};

describe("parser parity: preview (markdown-it) vs parse.rs", () => {
  it("wikilinks, embeds and body tags agree outside the known differences", () => {
    const bad: string[] = [];
    for (const c of pf.cases) {
      if (KNOWN_PARSE_DIFFS[c.src]) continue;
      const p = previewParse(c.src);
      const rw = rustWiki(c);
      const rt = c.bodyTags;
      if (JSON.stringify(p.wiki) !== JSON.stringify(rw) || JSON.stringify([...p.tags].sort()) !== JSON.stringify([...rt].sort()))
        bad.push(JSON.stringify({ src: c.src, preview: p, rust: { wiki: rw, tags: rt } }));
    }
    expect(bad).toEqual([]);
  });

  it("stripFrontmatter finds the same body start as split_frontmatter", () => {
    const bad: string[] = [];
    for (const c of pf.cases) {
      const s = stripFrontmatter(c.src);
      // Like the core's body_start, the body also starts after a lone BOM.
      const tsStart = c.src.length - s.body.length;
      if (tsStart !== c.bodyStartUtf16) bad.push(JSON.stringify({ src: c.src, ts: tsStart, rust: c.bodyStartUtf16 }));
    }
    expect(bad).toEqual([]);
  });

  it("FINDING-182: escaped \\[[link]] is plain text in the preview and in the core", () => {
    const c = pf.cases.find((c) => c.src.startsWith("\\#escaped"))!;
    expect(previewParse(c.src).wiki).toEqual(rustWiki(c));
  });

  it("FINDING-085: frontmatter closed by '---  ' is frontmatter in the UI and in the core", () => {
    const c = pf.cases.find((c) => c.src.startsWith("---\ntitle: x\n---  "))!;
    expect(stripFrontmatter(c.src).frontmatter === null).toBe(!c.hasFrontmatter);
  });

  it("FINDING-085: empty frontmatter (---/---) is frontmatter in the core and in the UI", () => {
    const c = pf.cases.find((c) => c.src.startsWith("---\n---\n"))!;
    expect(stripFrontmatter(c.src).frontmatter !== null).toBe(c.hasFrontmatter);
  });

  it("FINDING-186: the index, the preview and Live Preview agree: '(#tag)' is not a tag, ',#tag' and ';#tag' are", () => {
    const c = pf.cases.find((c) => c.src.startsWith("(#paren)"))!;
    const lp = [...c.src.matchAll(lpTagRe)].map((m) => m[2].toLowerCase());
    const preview = previewParse(c.src).tags;
    expect({ lp: lp.sort(), preview: preview.sort() }).toEqual({ lp: [...c.bodyTags].sort(), preview: [...c.bodyTags].sort() });
  });
});

describe("headings: core outline vs TS heading lookup (embeds, heading links)", () => {
  const KNOWN = new Set(["Bold title", "C#", "Setext", "code head", "quoted heading"]);

  it("extractSection finds every core heading outside the known differences", () => {
    const bad: string[] = [];
    for (const h of pf.headings)
      for (const x of h.headings) {
        if (KNOWN.has(x.text)) continue;
        if (extractSection(h.src, x.text) === null) bad.push(JSON.stringify({ src: h.src, heading: x.text }));
      }
    expect(bad).toEqual([]);
  });

  it("FINDING-187: headingsOf lists the core's headings (level, text, line)", () => {
    for (const h of pf.headings) expect({ src: h.src, headings: headingsOf(h.src) }).toEqual(h);
  });

  it("FINDING-187: heading links/embeds find every heading the outline shows (setext, C#, inline formatting)", () => {
    const missing: string[] = [];
    for (const h of pf.headings) for (const x of h.headings) if (extractSection(h.src, x.text) === null) missing.push(x.text);
    expect(missing).toEqual([]);
  });

  it("FINDING-187: extractSection skips a '# comment' line inside YAML frontmatter", () => {
    const src = "---\n# yaml comment\nk: v\n---\n# After\nbody\n";
    expect(extractSection(src, "yaml comment")).toBeNull();
  });
});
